### ISSUE TITLE
导出机时申请表单失败

### ISSUE THREAD

**Issue by xuelangZF** [luozhx/ehpc#520]
HPC 管理员下载机时申请信息表单出错。

```
[2017-05-18 09:16:57 +0800] [44548] [DEBUG] GET /admin/hpc/4/download/
[2017-05-18 09:16:57 +0800] [44548] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/feizhao/dropbox/ehpc/eHPC/user/authorize.py", line 63, in wrap
    return func(*args, **kwargs)
  File "/Users/feizhao/dropbox/ehpc/eHPC/admin/system_views.py", line 441, in machine_download
    pdfkit.from_string(render_template('admin/hpc/apply_pdf.html', apply=curr_apply), path, options=opt)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/pdfkit/api.py", line 70, in from_string
    configuration=configuration, cover_first=cover_first)
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/pdfkit/pdfkit.py", line 42, in __init__
    self.configuration = (Configuration() if configuration is None
  File "/Users/feizhao/.virtualenvs/ehpc/lib/python2.7/site-packages/pdfkit/configuration.py", line 27, in __init__
    'https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf' % self.wkhtmltopdf)
IOError: No wkhtmltopdf executable found: ""
If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
```

安装了  wkhtmltopdf 依然失败。

**Comment by luozhx** [comment]
>IOError: 'No wkhtmltopdf executable found':
>
>Make sure that you have wkhtmltopdf in your $PATH or set via custom configuration (see preceding section). >where wkhtmltopdf in Windows or which wkhtmltopdf on Linux should return actual path to binary.


可能whtmltopdf不在环境变量里，可以设置一下试试
```
config = pdfkit.configuration(wkhtmltopdf='/opt/bin/wkhtmltopdf'))
pdfkit.from_string(html_string, output_file, configuration=config)
```

**Comment by xuelangZF** [comment]
后台其他地方导出 pdf 好像没有这次的这个库啊，这里为什么要引入新的库。

**Comment by luozhx** [comment]
以前的PDF比较简单，是用reportlab直接绘制的。
现在这个是HTML转PDF，可以支持HTML和CSS样式。

**Comment by xuelangZF** [comment]
Soga。环境变量设置的话，是在 bash 中如何设置？

**Comment by luozhx** [comment]
应该是改` /etc/profile`吧，在最后面加
```
PATH=THE_SET_GLOBLE_ENV_PATH:$PATH;
```

**Comment by xuelangZF** [comment]
THE_SET_GLOBLE_ENV_PATH  这个变量从哪里获取的。你本机是在 windows 下的是吧。

**Comment by luozhx** [comment]
`THE_SET_GLOBLE_ENV_PATH`应该就是你想要增加的环境变量，放whtmltopdf的路径进去。
我是在ubuntu17.04测试的，安装完whtmltopdf就可以直接用，没有加过环境变量。

**Comment by xuelangZF** [comment]
好的，我试试吧。
